[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "openrlhf"
authors = [{name = "Jian Hu", email = "janhu9527@gmail.com"}]
dynamic = ["version", "description"]
